name: Google Chrome
on: [push]
jobs:
  Setup:
    runs-on: [macos-12, macos-11]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: What arch are we using?
        run: sysctl -n machdep.cpu.brand_string
      - name: Install Brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  Google-Chrome-Test:
    needs: [Setup]
    runs-on: [macos-12, macos-11]
    steps:
      - name: Run install for google chrome
        run: |
            brew reinstall google-chrome
            ls /Applications/
      - name: Get Codesign
        run: |
          codesign -d -r - /Applications/Google\ Chrome.app > /tmp/Google\ Chrome.txt
          cat /tmp/Google\ Chrome.txt
          echo "Done"

  Microsoft-Edge-Test:
    needs: [Google-Chrome-Test]
    runs-on: [macos-12, macos-11]
    steps:
      - name: Run install for Microsoft Edge
        run: |
            brew reinstall microsoft-edge
            ls /Applications/
      - name: Get Codesign
        run: |
          codesign -d -r - /Applications/Microsoft\ Edge.app > /tmp/Microsoft\ Edge.txt
          cat /tmp/Microsoft\ Edge.txt
          echo "Done"