name: Google Chrome
on: [push]
jobs:
  Setup:
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: What arch are we using?
        run: sysctl -n machdep.cpu.brand_string
      - name: Install Brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  Application-Test:
    needs: [Setup]
    strategy:
      matrix:
        app: [google-chrome, dialpad]
    runs-on: macos-12
    steps:
      - name: Run install for ${{ matrix.app }}
        run: |
            brew reinstall ${{ matrix.app }} > /tmp/brewinstall.txt
            echo "getting brewinstall log"
            cat /tmp/brewinstall.txt
            echo "Grepping brewinstall"
            $${{ matrix.app }}path = grep -E "'\/Applications/.*.app'" /tmp/brewinstall.txt | awk -F" to " '{print $2}'
            echo "^^^ Thats the app path"
            echo $${{ matrix.app }}path 
            echo "^^^ That is the var"
      # - name: Get Codesign
      #   run: |
      #     codesign -d -r - /Applications/* > /tmp/applist.txt
      #     cat /tmp/applist.txt
      #     echo "Done"
      - name: Uninstall ${{ matrix.app }}
        run: |
            brew uninstall ${{ matrix.app }}
            ls -ltr /Applications/

  # Microsoft-Edge-Test:
  #   needs: [Google-Chrome-Test]
  #   strategy:
  #     matrix:
  #       os: [macos-12]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Run install for Microsoft Edge
  #       run: |
  #           brew reinstall microsoft-edge
  #           ls /Applications/
  #     - name: Get Codesign
  #       run: |
  #         codesign -d -r - /Applications/Microsoft\ Edge.app > /tmp/Microsoft\ Edge.txt
  #         cat /tmp/Microsoft\ Edge.txt
  #         echo "Done"

  # Dialpad-Test:
  #   needs: [Google-Chrome-Test, Microsoft-Edge-Test]
  #   strategy:
  #     matrix:
  #       os: [macos-12]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Run install for Dialpad
  #       run: |
  #           brew install dialpad
  #           ls /Applications/
  #     - name: Get Codesign
  #       run: |
  #         codesign -d -r - /Applications/Dialpad.app > /tmp/Dialpad.txt
  #         cat /tmp/Dialpad.txt
  #         echo "Done"